spring:
  datasource:
    url: jdbc:postgresql://localhost:5437/cart-db
    username: cart
    password: cart
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5 #Настройки пула соединений (HikariCP — дефолтный пул в Spring Boot).
      connection-timeout: 30000


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true #Показывать SQL-запросы в логах
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  redis:
    host: redis  # Имя сервиса в Docker Compose
    port: 6379


resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 100
        failureRateThreshold: 60
        slowCallRateThreshold: 50
        slowCallDurationThreshold: 2s
        minimumNumberOfCalls: 20
        waitDurationInOpenState: 30s
        permittedNumberOfCallsInHalfOpenState: 10
        automaticTransitionFromOpenToHalfOpenEnabled: true
    instances:
      warehouseService:
        baseConfig: default
        waitDurationInOpenState: 15s
        recordExceptions: # Какие исключения считать ошибками
        ignoreExceptions: # Какие исключения игнорировать
         - ru.yandex.practicum.exception.WarehouseServiceException

logging:
  level:
    org.springframework.cloud.openfeign: DEBUG
    ru.yandex.practicum.RequestLoggingFilter: INFO
    io.github.resilience4j: DEBUG
    ru.yandex.practicum.warehouse.feign.WarehouseServiceClient: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,circuitbreakers
  endpoint:
    health:
      show-details: always
    circuitbreakers:
      enabled: true

cart:
  process:
    max-attempts: 3 #количество попыток отправки корзины