spring:
  datasource:
    url: jdbc:postgresql://localhost:5440/delivery-db
    username: delivery
    password: delivery
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5 #Настройки пула соединений (HikariCP — дефолтный пул в Spring Boot).
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true #Показывать SQL-запросы в логах
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

logging:
  level:
    ru.yandex.practicum.RequestLoggingFilter: INFO