grpc:
  server:
    port: 59091


kafka:
  topics:
    sensor_events_topic: telemetry.sensors.v1
    hub_events_topic: telemetry.hubs.v1

logging:
  level:
    io.grpc: DEBUG
    org:
      zalando:
        logbook: DEBUG
      springframework:
                web: DEBUG