spring:
  application:
    name: collector
  config:
    import: configserver:http://localhost:8888
  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: true
logging:
  level:
    org.springframework.cloud: DEBUG
    org.springframework.boot: INFO
    ru.yandex.practicum: DEBUG