grpc:
  client:
    hub-router:
      address: 'static://localhost:59090'
      enable-keep-alive: true
      keep-alive-without-calls: true
      negotiation-type: plaintext

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/analyzer-db
    username: analyzer
    password: analyzer
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5 #Настройки пула соединений (HikariCP — дефолтный пул в Spring Boot).
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true #Показывать SQL-запросы в логах
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true